// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using Peleas.Models;
using System;

namespace Peleas.Migrations
{
    [DbContext(typeof(MvcContext))]
    [Migration("20181110214409_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Peleas.Models.Control", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Contraseña");

                    b.Property<string>("Nombre");

                    b.HasKey("ID");

                    b.ToTable("Control");
                });

            modelBuilder.Entity("Peleas.Models.Lucha", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos")
                        .IsRequired();

                    b.Property<int>("Celular");

                    b.Property<string>("ConfirmarContraseña");

                    b.Property<string>("ConfirmarCorreo");

                    b.Property<string>("Contraseña")
                        .IsRequired();

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("Nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Usu")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Lucha");
                });

            modelBuilder.Entity("Peleas.Models.Luchador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos")
                        .IsRequired();

                    b.Property<int>("Celular");

                    b.Property<string>("ConfirmarContraseña");

                    b.Property<string>("ConfirmarCorreo");

                    b.Property<string>("Contraseña")
                        .IsRequired();

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("Nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Usu")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Luchador");
                });
#pragma warning restore 612, 618
        }
    }
}
